[package]
name = "bong"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
crate-type = ["cdylib"]

[dependencies]
bindings = { path = "bindings" }
windows = "0.21.1"

widestring = "0.5.0"
anyhow = "1.0"
